#!/usr/bin/env bash
# This script displays listening ports along with PID and program name.

# Display active internet connections with listening sockets and related programs
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
netstat -tuln | awk '$6 == "LISTEN" {print $1, $4, $NF}' | sed 's/.*://;s/:::/[::]:/' | sed -e 's/\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}/& /'

# Display active UNIX domain sockets with listening servers and related programs
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
netstat -x | awk '$6 == "LISTEN" {print $1, $2, $3, $4, $5, $6, $7}' | sed 's/\// /' | sed 's/^[^ ]* \([^ ]*\) [^ ]* [^ ]* [^ ]* [^ ]* \([^ ]*\)/\1    \2/' | sed -e 's/@/ /'


