#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

# Ensure Nginx is installed
apt-get update
apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart

