#!/usr/bin/env bash
# This script configures and restarts Nginx to listen on port 80

apt-get install -y nginx
sed -i 's/listen 80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
service nginx restart

