#!/usr/bin/env bash
# This script displays information about users in /etc/passwd using a while loop with IFS

# Read /etc/passwd line by line using while loop with IFS set to :
while IFS=':' read -r username _ userid groupid _ home_directory shell; do
    # Extract additional information using userid and username
    user_info=$(grep "^${username}:" /etc/passwd | cut -d ":" -f 5)
    # Extract password information from /etc/shadow
    password=$(grep "^${username}:" /etc/shadow | cut -d ":" -f 2)
    # Display user information
    echo "The user $username is part of the group $groupid gang, lives in $home_directory, and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd

