#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and associated messages using a while loop and a case statement

# Initialize counter
counter=1

# Loop from 1 to 20
while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "$counter and bad luck from China"
            ;;
        9)
            echo "$counter and bad luck from Japan"
            ;;
        17)
            echo "$counter and bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac
    # Increment counter
    ((counter++))
done

