#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine it's executed on

# Use ip addr to display IPv4 addresses of active interfaces
ifconfig | grep -oE 'inet ([0-9]{1,3}\.){3}[0-9]{1,3}' | cut -d ' ' -f 2
